sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - sudo apt-get install python3-nose
  - pip install codecov
  - pip install -r requirements.txt
# command to run tests
script: nosetests ./sport_analyzer/test/utest.py  --cover-branches --with-coverage --cover-erase --cover-package=sport_analyzer
after_success:
- codecov
